server:
  port: 4000

spring:
  application:
    name: maxtunnel-em
  # dev环境
  profiles:
    active: dev
  # 数据源
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: bandweaver
    password: 123456
    url: jdbc:oracle:thin:@localhost:1521:MAXTUNNELDB

# mybaits 模块配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bandweaver.maxtunnelem.entity

feign:
   hystrix:
     enabled: true

# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:1025/eureka/


