server:
  port: 7000

spring:
  application:
    name: maxtunnel-shiro
  # dev环境
  profiles:
    active: dev
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/common?characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379


# mybaits 模块配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bandweaver.maxtunnelshiro.entity

feign:
   hystrix:
     enabled: true

bandweaver:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    exchangeName: BANDWEAVER_MAXTUNNEL_EXCHANGE
  redis:
    permissionKey: permissionSet

# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 12
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:1025/eureka/



